### ISSUE TITLE
In Android 11, Error receiving broadcast Intent in ChildBroadcastReceiver

### ISSUE THREAD

**Issue by Neox76** [leolashkevych/frida-scripts#1]
In android-broadcast-receiver.js, using registerReceiver, when an intent is received with Android 11, it crashes with the following error:

> java.lang.RuntimeException: Error receiving broadcast Intent { act=com.some.example.intent flg=0x10 (has extras) } in ChildBroadcastReceiver@93336e1
> 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1577)
> 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:233)
> 	at android.app.ActivityThread.main(ActivityThread.java:8052)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.perfdebug.BroadcastMonitor.monitorReceiveBegin()' on a null object reference
> 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1563)
> 	... 8 more

If it can help, the attached process is a Unity game.

**Comment by leolashkevych** [comment]
I tried reproducing this on Android 11 and 12 and I did not get a crash. Can you share the APK you're using and the intent filter you wanted to catch?

**Comment by Neox76** [comment]
The game is Pokemon Go. The intent is a custom one, so basically anything. (like com.app.package.RECV)
Let me know if you still can't reproduce it.
